spring:
  # redis
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: czy1024 # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-idle: 8
        max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
  timeout: 1000.0 # 连接超时时间（毫秒）


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://f.xicc.cc:23305/spring-demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: luna
    password: czy1024

  # elasticsearch
  elasticsearch:
    rest:
      username: luna
      password: czy1024
      # 集群
      uris: [ http://localhost:9200 ]
      connection-timeout: 5000
      read-timeout: 30000


mybatis:
  mapperLocations: classpath:mapper/es/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  typeAliasesPackage: com.luna.springdemo.*.entity  # 注意：对应实体类的路径
  configLocation: classpath:mybatis/mybatis-config.xml