spring:
  redis:
    host: f.xicc.cc #哨兵模式下不用配置
    port: 23418 # 哨兵模式下不用配置
    password: czy1024
    jedis:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 20000
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 10
#    sentinel:
#      master: mymaster
#      nodes: f.xicc.cc:23419,f.xicc.cc:23420,f.xicc.cc:23421
#    cluster:
#      nodes: f.xicc.cc:23416,f.xicc.cc:23417,f.xicc.cc:23418
server:
  port: 8088
