spring:
  redis:
    host: localhost
    port: 6379
    password: czy1024
    jedis:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 20000
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 10
#    sentinel:
#      master: mymaster
#      nodes: f.xicc.cc:23419,f.xicc.cc:23420,f.xicc.cc:23421

#       - 192.168.2.110:26379
#       - 192.168.2.110:26380
#       - 192.168.2.110:26381

server:
  port: 8088
